reset_base_tool_tf: [0.3798798, 0.4354138, 0.5674016, -2.62026, 1.097083, 2.581592]
reset_joint_pos: [-1.652892, -0.679576, 2.574493, -0.8140897, -0.8237059, 0.9212675, -0.9110789]
# init_gripper_random_lim: [.01, .01, .01, .1, .1, .1]  # 1 cm translation in all dimensions, roughly 5 degrees
# init_gripper_random_lim: [.01, .01, .01, 0.0, 0.0, .1]  # 1 cm translation in all dimensions, roughly 5 degrees
init_gripper_random_lim: [.03, .03, .03, 0.0, 0.0, .3]  # 1 cm translation in all dimensions, roughly 5 degrees
max_real_time: 12  # in seconds
sts_num_contact_tac_thresh: 600
sts_num_contact_vis_thresh: 200
stiffness_params: {"translational_stiffness": 200.0,
                   "rotational_stiffness": 10.0,
                   "nullspace_stiffness": 0.5}
damping_params: {"translational_damping": 1.0,
                   "rotational_damping": 1.0,
                   "nullspace_damping": 1.0}

# making poses/actions more "realistic", as if we had a mobile base instead of fixed arm to cabinet transform
pose_relative: 'reset'        # options: reset, base -- reset is relative to reset frame, base is to base
t_action_base_frame: 't'      # b or t
r_action_base_frame: 't'      # b or t

# path relative to contact_panda_envs/envs