dataset_name: single-plate-noisy
dataset_config:
  _target_: datasets.MultimodalManipBCDataset
  data_dirs: ["/home/rbslab/place-from-pick-learning/datasets/srj/single-plate-noisy_128-episodes_fd4b07b3e6224701bddc87f54ccb95d7"] 
  rotation_representation: ${rotation_representation}
  n_frame_stacks: ${n_frame_stacks}
  seq_length: ${seq_length}
  load_tensor: True
  device: ${device}
  n_max_episodes: null
  use_tactile: False