dataset_name: single-plate-noisy
dataset_config:
  _target_: datasets.MultimodalManipBCDataset
  data_dirs: ["/home/rbslab/place-from-pick-learning/datasets/kin_test/kin_demonstration_128-episodes/data"] 
  rotation_representation: ${rotation_representation}
  n_frame_stacks: ${n_frame_stacks}
  seq_length: ${seq_length}
  load_tensor: True
  device: ${device}
  n_max_episodes: null
  use_tactile: False