env_name: placefrompick_demo
env_config:
  _target_: place_from_pick_learning.envs.place_from_pick_env.PlaceFromPickEnv
  home_joints: [0.08590221, -0.36777158, 0.17080808, -1.45435247, 0.17139973, 1.11786831, 1.1647684]
  img_res: [128, 128]
  gripper_close_time: 1.0
  obs_act_fixed_time: 0.15
  dt: 0.20
  retrieval_pose_filename: /home/rbslab/place-from-pick-learning/data/hardcoded_grasps/srj/retrieval_pose.pkl
  retrieval_pose_noise: 0.0
  grasp_pose_filename: /home/rbslab/place-from-pick-learning/data/hardcoded_grasps/srj/grasp_pose.pkl
  use_pregrasp: False
  use_compliant_grasping: False
  sts_config_dir: null