dataset_name: single-plate_varied-initial
dataset_config:
  _target_: datasets.MultimodalManipBCDataset
  data_dirs: ["/home/rbslab/place-from-pick-learning/datasets/panda/dt-0.2_img-res-128_episodes-64_all-blinds-down_noisy_25420d794afa44a5b52aec0b1c68ae85"] 
  rotation_representation: ${rotation_representation}
  n_frame_stacks: ${n_frame_stacks}
  seq_length: ${seq_length}
  load_tensor: True
  device: ${device}